package com.warehouse.dto;

import java.util.List;

public record LiveMapRobotStateDto(Long robotId,
                                   String robotName,
                                   String robotCode,
                                   String color,
                                   Integer batteryLevel,
                                   Integer batteryPercent,
                                   Integer batteryDrainPercent,
                                   String batteryDisplayText,
                                   String batteryWarningLevel,
                                   boolean lowBattery,
                                   boolean criticalBattery,
                                   boolean energySavingMode,
                                   boolean chargingRequired,
                                   String batteryMessage,
                                   boolean charging,
                                   Integer chargingRecoveredPercent,
                                   String chargingDisplayText,
                                   String movementMode,
                                   String movementModeDisplay,
                                   Integer waypointsPerBatteryPercent,
                                   String batteryDrainMode,
                                   String primaryStrategyName,
                                   String currentActiveStrategyName,
                                   String strategyMessage,
                                   String robotStatus,
                                   Long missionId,
                                   String requestCode,
                                   String status,
                                   String executionStep,
                                   String currentPositionKey,
                                   String nextPositionKey,
                                   double segmentProgress,
                                   String targetZone,
                                   String targetLocationCode,
                                   List<LiveMapRouteStepDto> route,
                                   String message,
                                   boolean waiting,
                                   String blockedSegment) {
}
